services:
  flowers-database:
    image: postgres:alpine
    container_name: flowers-database
    ports:
      - "6001:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flowers

  flowers-service:
    image: flowers-service
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flowers-service
    ports:
      - "6002:8085"
    environment:
      - server.port=8085
      - spring.datasource.url=jdbc:postgresql://flowers-database:6001/flowers
      - spring.datasource.username=postgres
      - spring.datasource.password=password
    restart: "no"
    depends_on:
      - flowers-database

